name       : kmbox
version    : 18.12.3
release    : 20
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kmbox-18.12.3.tar.xz : 13a88db1ab0d628a3053a0d6ab5d89cd2f6cbadb3082b52e5dc7048516a10841
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
