name       : kmbox
version    : 18.04.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kmbox-18.04.0.tar.xz : 1334e0ca3f4d3de5a5d7a605cfd448c26bcda40c246ef5ac466a4a217b5c9262
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : KMBox provides API to access emails in storages in the MBox format.
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
