name       : kmbox
version    : 18.08.3
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/kmbox-18.08.3.tar.xz : 8745a07ff35c9011aee46e2fdfeadc0405389577cec46ea291fdf2a88a279910
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
