name       : kmbox
version    : 23.04.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/kmbox-23.04.0.tar.xz : d587f87fb5358e8d7f0495c7e9e6dfea4a4de33671387a71fd4033145c26386b
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - kcodecs-devel
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
