name       : kmbox
version    : 18.04.1
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/kmbox-18.04.1.tar.xz : 187b2a0677296469caefb079dcb8f7b54c79e81a46e3881cae4aabb3a6b7ec17
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : KMBox provides API to access emails in storages in the MBox format.
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
