name       : kmbox
version    : 17.08.1
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/kmbox-17.08.1.tar.xz : 4df08ff60633306a740b16896c403056b3ff48b7f1ec23cf0f8111bf9291f22d
license    : LGPL-2.1
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format.
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kmime-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
