name       : kmbox
version    : 20.04.3
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/kmbox-20.04.3.tar.xz : 50b2a8ba98cf24117ba66ddb9b51d1db575998b36ad1aa15fec0135446cc7561
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
