name       : kmbox
version    : 17.12.3
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/kmbox-17.12.3.tar.xz : f5c95218afe3e3dcc0d708497e0b918578e8d5ad1cde9f875432f3c57863a997
license    : LGPL-2.1
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format.
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kmime-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
