name       : kmbox
version    : 22.04.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kmbox-22.04.0.tar.xz : 619a292f7738162e15ad74b46d3a5f5ed3b8a696e5f5768845148db1d19752fb
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - kcodecs-devel
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
