name       : kmbox
version    : 21.08.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kmbox-21.08.0.tar.xz : 8aed28b29321f25271e0a3a423eb01164c90795d5951c335ac15b222997844f5
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - kcodecs-devel
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
