name       : kmbox
version    : 23.04.2
release    : 65
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kmbox-23.04.2.tar.xz : 6c893e105aa88785a90c936e21cbc9c961d837982fee66e1f121625b438ebea9
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - kcodecs-devel
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
