name       : kmbox
version    : 20.12.2
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kmbox-20.12.2.tar.xz : 14068aab474b36075c4eb422fd0ed5fc2121de7e62186f74d34235f206d0e664
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - kcodecs-devel
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
