name       : kmbox
version    : 17.08.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kmbox-17.08.3.tar.xz : 11a3a907346966864cb0b98e40b5b7b943f222214ab7196b7dbb04ed0a00c055
license    : LGPL-2.1
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format.
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kmime-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
