name       : kmbox
version    : 17.04.1
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/kmbox-17.04.1.tar.xz : 27b715ec62ee3c9f816d86d36e8fe8ea3d5972c2fabdee7e4f0a7351511dd899
license    : LGPL-2.1
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format.
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kmime-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
