name       : kmbox
version    : 17.04.0
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.0/src/kmbox-17.04.0.tar.xz : d8e7c04141ab16e6c07ea1c0a48cfc8a3de36d01d47b7ac5cc5bc19ebd182e00
license    : LGPL-2.1
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format.
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kmime-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
