name       : kmbox
version    : 19.04.1
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/kmbox-19.04.1.tar.xz : 701eda3a4831ed0daf9bd14a93ff845f42e4f93c6ca16d83ebda958c27021fc0
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
