name       : kmbox
version    : 19.12.1
release    : 30
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/kmbox-19.12.1.tar.xz : 7442fd3a421a917a3f27e47259a7da7e08ff6191290a0e9e67c67005c82c606a
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMBox provides API to access emails in storages in the MBox format
description: |
    KMBox provides API to access emails in storages in the MBox format.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kmime-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
